[versions]
ktor = "1.6.7"
room = "2.4.1"
okhttp = "5.0.0-alpha.4"
moshi = "1.13.0"
hilt = "2.40.5"
retrofit = "2.9.0"
aboutLibraries = "10.0.0-b03"


[libraries]
desugarJdkLibs = "com.android.tools:desugar_jdk_libs:1.1.5"
gradle-tools = "com.android.tools.build:gradle:7.1.2"
gradle-kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
gradle-kotlinSerialization = "org.jetbrains.kotlin:kotlin-serialization:1.6.10"
gradle-hilt = "com.google.dagger:hilt-android-gradle-plugin:2.39.1"
gradle-google = "com.google.gms:google-services:4.3.10"
gradle-firebaseCrashlytic = "com.google.firebase:firebase-crashlytics-gradle:2.8.1"
gradle-benmanes = "com.github.ben-manes:gradle-versions-plugin:0.42.0"


ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-jsoup = "com.tfowl.ktor:ktor-jsoup:1.6.4"

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }


okhttp-okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-doh = { module = "com.squareup.okhttp3:okhttp-dnsoverhttps", version.ref = "okhttp" }


moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
moshi-moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }

retrofit-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshiConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
retrofit-okHttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }



hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-androidcompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-compiler = "androidx.hilt:hilt-compiler:1.0.0"
hilt-worker = "androidx.hilt:hilt-work:1.0.0"
hilt-androidtest = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }


firebase-bom = "com.google.firebase:firebase-bom:29.0.4"
firebase-analyticKtx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytic = { module = "com.google.firebase:firebase-analytics" }




timber = "com.jakewharton.timber:timber:5.0.1"
multidex = "androidx.multidex:multidex:2.0.1"
tachiyomi = "io.github.kazemcodes:core-androidRelease:1.0.1-SNAPSHOT"
okio = "com.squareup.okio:okio:3.0.0"
quickjsAndroid = "app.cash.quickjs:quickjs-android:0.9.2"
quickjsJvm = "app.cash.quickjs:quickjs-jvm:0.9.2"
jsoup = "org.jsoup:jsoup:1.14.3"



[bundles]


[plugins]
