[versions]



junitAndroidExtVersion = "1.1.4-alpha03"

[libraries]
junit4 = "junit:junit:4.13.2"
extJunit = "androidx.test.ext:junit:1.1.3"
espresso = "androidx.test.espresso:espresso-core:3.4.0"
junitAndroidExt = "androidx.test.ext:junit:1.1.4-alpha03"
coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.5.1"
truth = "com.google.truth:truth:1.1.3"
testRunner = "androidx.test:runner:1.4.0"



[bundles]


[plugins]
