blank_issues_enabled: false
contact_links:
  - name: ⚠️ Extension/source issue
    url: https://github.com/IReaderorg/IReader-extensions/issues/new/choose
    about: Issues and requests for extensions and sources should be opened in the tachiyomi-extensions repository instead
  - name: 📦 IReader extensions
    url: https://github.com/IReaderorg/IReader-extensions/tree/master/sources
    about: List of all available extensions with download links