name: CI
on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
          all_but_latest: true

      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Build app and run unit tests
        uses: gradle/gradle-command-action@v2
        with:
          arguments: :android:assembleStandardRelease :android:testStandardReleaseUnitTest

      # Sign APK and create release for tags

      - name: Get tag name
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'IReaderorg/IReader'
        run: |
          set -x
          echo "VERSION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Sign APK
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'IReaderorg/IReader'
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: android/build/outputs/apk/standard/release
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}

      - name: Clean up build artifacts
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'IReaderorg/IReader'
        run: |
          set -e

          mv android/build/outputs/apk/standard/release/android-standard-universal-release-unsigned-signed.apk IReader-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum IReader-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_UNIVERSAL_SHA=$sha" >> $GITHUB_ENV

          cp android/build/outputs/apk/standard/release/android-standard-arm64-v8a-release-unsigned-signed.apk IReader-arm64-v8a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum IReader-arm64-v8a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARM64_V8A_SHA=$sha" >> $GITHUB_ENV

          cp android/build/outputs/apk/standard/release/android-standard-armeabi-v7a-release-unsigned-signed.apk IReader-armeabi-v7a-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum IReader-armeabi-v7a-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_ARMEABI_V7A_SHA=$sha" >> $GITHUB_ENV

          cp android/build/outputs/apk/standard/release/android-standard-x86-release-unsigned-signed.apk IReader-x86-${{ env.VERSION_TAG }}.apk
          sha=`sha256sum IReader-x86-${{ env.VERSION_TAG }}.apk | awk '{ print $1 }'`
          echo "APK_X86_SHA=$sha" >> $GITHUB_ENV

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'IReaderorg/IReader'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: IReader ${{ env.VERSION_TAG }}
          body: |
            ---

            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | Universal | ${{ env.APK_UNIVERSAL_SHA }}
            | arm64-v8a | ${{ env.APK_ARM64_V8A_SHA }}
            | armeabi-v7a | ${{ env.APK_ARMEABI_V7A_SHA }}
            | x86 | ${{ env.APK_X86_SHA }} |
          files: |
            IReader-${{ env.VERSION_TAG }}.apk
            IReader-arm64-v8a-${{ env.VERSION_TAG }}.apk
            IReader-armeabi-v7a-${{ env.VERSION_TAG }}.apk
            IReader-x86-${{ env.VERSION_TAG }}.apk
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
